### ISSUE TITLE
Build multiple architectures for the default ryuk image

### ISSUE THREAD

**Issue by yjwong** [testcontainers/testcontainers-node#249] opened 2021-08-02 04:34 UTC
Hi! 

I noticed that the default testcontainers ryuk image is [cristianrgreco/ryuk:0.4.0](https://hub.docker.com/layers/cristianrgreco/ryuk/0.4.0/images/sha256-e1f13eca329e43f03f38786406507c65162e63acd35e7d4c3708b25a6c80f791?context=explore), which only supports `linux/amd64`, but the upstream `testcontainers/ryuk` image does support multiple architectures on its latest tag (0.3.1).

Is it possible to either:

1. Support multiple architectures for the `cristianrgreco/ryuk` image, or
2. Switch to the upstream image? 

I know it's possible to set a custom image using `RYUK_CONTAINER_IMAGE` but it'd be really nice to have this work out of the box for non-x86 machines like on Apple Silicon or Raspberry Pi.

**Comment by cristianrgreco** [comment] 2021-08-02 08:20
Hi @yjwong, thanks for raising! 

For a bit of context we had this issue a while back where ryuk wasn't cleaning up images: https://github.com/testcontainers/testcontainers-node/issues/189. A PR was raised on the upstream ryuk to fix this: https://github.com/testcontainers/moby-ryuk/pull/25. It's been merged but not released which is why `cristianrgreco/ryuk:0.4.0` was created.

@bsideup would it be possible to release https://github.com/testcontainers/moby-ryuk/pull/25 to ryuk?

@yjwong if not I will look into publishing a multi-arch alternative.

**Comment by rnorth** [comment] 2021-08-02 11:04
We had a problem with the multi-arch build, which was failing on an apparent regression in buildkit/qemu. We never had time to investigate more thoroughly, but it looks like [this PR](https://github.com/testcontainers/moby-ryuk/pull/26) now builds correctly when using latest versions of buildx and qemu, so we should be good to publish a new multi-arch version of ryuk.

I'll get onto that later today.

**Comment by rnorth** [comment] 2021-08-03 09:17
OK, v0.3.2 of Ryuk is now published with this fix! https://hub.docker.com/repository/docker/testcontainers/ryuk/tags

**Comment by cristianrgreco** [comment] 2021-08-03 09:56
Released in [7.18.2](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.18.2), thanks @rnorth and @yjwong 🙂

**Closed by cristianrgreco** 2021-08-03 09:56 UTC
Labels: enhancement

**Comment by yjwong** [comment] 2021-08-03 10:08
That was quick, thanks @cristianrgreco @rnorth!
