### ISSUE TITLE
[Gitlab CI] Could not find a working container runtime strategy

### ISSUE THREAD

**Issue by zotijs** [testcontainers/testcontainers-node#786] opened 2024-06-25 07:22 UTC
Job configuration:

```
test:
  stage: test
  extends: .test_application
  services:
    - name: docker:dind
      alias: docker
      # explicitly disable tls to avoid docker startup interruption
      command: ['--tls=false']
  variables:
    DOCKER_HOST: 'tcp://docker:2375'
    DOCKER_TLS_CERTDIR: ''
    DEBUG: testcontainers*
  only:
    - merge_requests
```

I am getting `Could not find a working container runtime strategy` when I am trying to start the testcontainer in jest's `globalSetup`

Debug print:

```
2024-06-21T14:39:33.532Z testcontainers [DEBUG] Testing container runtime strategy "TestcontainersHostStrategy"...
2024-06-21T14:39:33.534Z testcontainers [DEBUG] Found custom configuration: dockerHost: "tcp://docker:2375"
2024-06-21T14:39:33.534Z testcontainers [DEBUG] Testing container runtime strategy "ConfigurationStrategy"...
2024-06-21T14:39:33.563Z testcontainers [DEBUG] Container runtime strategy "ConfigurationStrategy" does not work
2024-06-21T14:39:33.563Z testcontainers [DEBUG] Testing container runtime strategy "UnixSocketStrategy"...
2024-06-21T14:39:33.563Z testcontainers [DEBUG] Testing container runtime strategy "RootlessUnixSocketStrategy"...
2024-06-21T14:39:33.564Z testcontainers [DEBUG] Testing container runtime strategy "NpipeSocketStrategy"...
```

More details:
- the runner is a docker executor
- the image of the test is node alpine

_Originally posted by @zotijs in https://github.com/testcontainers/testcontainers-node/issues/768#issuecomment-2188135321_

**Comment by cristianrgreco** [comment] 2024-06-25 08:48
Duplicate of https://github.com/testcontainers/testcontainers-node/issues/786

**Closed by cristianrgreco** 2024-06-25 08:48 UTC

**Comment by zotijs** [comment] 2024-06-25 08:53
@cristianrgreco the other issue is closed and it is was windows related. There was another comment in the initial thread for gitlab ci, requesting the Issue to be re-opened.

Can you please provide some guidance on running testcontainers-node in gitlab ci? The sidecar service setup that is provided in [testcontainers-java](https://java.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/) does not work (or I am missing something).

**Comment by cristianrgreco** [comment] 2024-06-25 08:57
> @cristianrgreco the other issue is closed and it is was windows related. There was another comment in the initial thread for gitlab ci, requesting the Issue to be re-opened.
> 
> Can you please provide some guidance on running testcontainers-node in gitlab ci? The sidecar service setup that is provided in [testcontainers-java](https://java.testcontainers.org/supported_docker_environment/continuous_integration/gitlab_ci/) does not work (or I am missing something).

Duplicate link updated
