### ISSUE TITLE
Throwable containers using Ryuk

### ISSUE THREAD

**Issue by kolychev** [testcontainers/testcontainers-node#118] opened 2020-09-11 03:42 UTC
Hello,

Is there any plans to implement throwable containers feature, when containers are automatically killed when not used by any tests anymore ?
In java testcontainers project this is made using special ryuk container which as I understand is pinged by test framework while test is running.
Would be great if same technics could be implemented in testcontainers-node.

Example use case when this technic is helpful: when we debug some tests in IDE, we usually have started container by some code in beforeEach/beforeAll section. After that we have breakpoint somewhere, debug code/test execution and stop running test from IDE. No afterEach/afterAll section is executed and no chance to stop container we started in before* section. So in the end we have running container on developer's system. Next debug session will start another container that might be not stopped by same reasons. In the end of the day we have tons of containers that consume memory/cpu and slow down whole system.

Please share your thought about it.

**Comment by cristianrgreco** [comment] 2020-09-11 08:02
Hi @kolychev, sounds like a great idea. 
I don't know anything about ryuk but I'll look into it when I get some time. Of course PRs are welcome!

**Comment by kolychev** [comment] 2020-09-11 08:16
Unfortunately I don't know much myself, but maybe @bsideup could share some links where to check how java testcontainers works with https://github.com/testcontainers/moby-ryuk

**Comment by bsideup** [comment] 2020-09-11 20:28
Most of it is described in Ryuk's README:
1. maintain a TCP connection to Ryuk
2. register everything you start to Ryuk (via labels). In testcontainers-java, we register a single label (session id) and then assign it to every container/network/volume/image/whatever we create, for example
3. if the TCP connection drops, reconnect
4. Ryuk will start removing containers if there was no reconnection for the past N seconds

**Comment by cristianrgreco** [comment] 2020-09-14 11:34
Hey @bsideup, I've noticed that even though I've labelled images built via Dockerfiles, ryuk isn't removing them - am I missing something? I see from the code that the images are pruned, rather than removed by label so perhaps this is expected?

Also I'm currently mounting '/var/run/docker.sock`, will that work for Windows?

**Comment by cristianrgreco** [comment] 2020-09-16 08:37
@kolychev I'm a bit stumped with this one. The implementation is done and it works well when running this library's tests.

The problem I have is that if you were to start a new container, we would also start a ryuk container. The problem is that when tests end, this container keeps running, meaning that the node process doesn't exit. Without having every consumer of the library call something like `TestContainers.shutdown()` after all tests run I'm not sure how to tackle this. Have you any ideas?

**Comment by bsideup** [comment] 2020-09-16 08:48
> if you were to start a new container, we would also start a ryuk container

FYI the way Ryuk is designed is to be started once for the session, not per container

> The problem is that when tests end, this container keeps running, meaning that the node process doesn't exit

Ryuk will wait up to N seconds and then destroy everything registered to it and then exit

>  There also doesn't seem to be a reliable way to do something on shutdown, as this depends on the test frameworks.

https://stackoverflow.com/a/5397119/1826422

**Comment by cristianrgreco** [comment] 2020-09-16 08:56
Thanks @bsideup, just a few clarifications

> FYI the way Ryuk is designed is to be started once for the session, not per container

The implementation I've done is also that we have a single ryuk container, but it's started if/when a container/network starts. Do you see any issues with this approach?

> Ryuk will wait up to N seconds and then destroy everything registered to it and then exit

Yep, the problem is that the tests will hang for 10s until ryuk exits

> https://stackoverflow.com/a/5397119/1826422

Damn, I had tried this and it didn't work - I just double checked and the reason it didn't work is because of the default 10s wait we have to stop a container gracefully 😅  Setting this to 0ms works!

**Comment by bsideup** [comment] 2020-09-16 08:58
> it's started if/when a container/network/compose environment starts. Do you see any issues with this approach?

No, just make sure that this "lazy" behaviour is implemented correctly and handles everything

> Yep, the problem is that the tests will hang for 10s until ryuk exits

There is absolutely no need to wait for Ryuk. You start it, you register a label to it, and then you forget about it.

> the default 10s wait we have to stop a container gracefully

Hm, I wonder why would you stop them gracefully. This is for testing, meaning that there is no point in gracefully stopping things IMO

**Comment by cristianrgreco** [comment] 2020-09-16 09:02
> There is absolutely no need to wait for Ryuk. You start it, you register a label to it, and then you forget about it.

That's my wish, but unless I come back to shut it down the node process will run for the 10s needed for ryuk to stop.

> Hm, I wonder why would you stop them gracefully. This is for testing, meaning that there is no point in gracefully stopping things IMO

Ah interesting, I'm not sure where I got the default of 10s from, but yeah I can change it to zero, I'll raise a separate PR for it.

Things are working well now with the `process.exit`, thanks @bsideup!

**Comment by bsideup** [comment] 2020-09-16 09:06
> That's my wish, but unless I come back to shut it down the node process will run for the 10s needed for ryuk to stop. For the node process to terminate gracefully all handles need to be closed

Ah, okay, now I see why :) So there is no option to do some kind of a "daemon" TCP connection that does not prevent the runtime from exiting?

Anyways, I am glad that `process.exit` works fine for you 👍 Glad to be helpful :)

**Comment by cristianrgreco** [comment] 2020-09-16 10:44
Dang, `process.exit` isn't working when running the tests in band or in CI 😞 

> Jest did not exit one second after the test run has completed. 
> 
> This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.

**Comment by kolychev** [comment] 2020-09-16 11:37
First of all my congratulations to you, there is a good progress with this !

As for open socket to Ryuk, did you try socket.unref() method after you open socket: https://nodejs.org/api/net.html#net_socket_unref

Not sure if you still can send docker labels to unref'ed socket, but I think it is worth to try.

**Comment by cristianrgreco** [comment] 2020-09-16 13:04
Thanks @kolychev! 

I gave unref a go but it's the same issue, the problem is it's not just the socket which keeps running, but the container itself

**Comment by cristianrgreco** [comment] 2020-09-16 16:07
I found the issue. The open handle isn't the container, it's the log stream! It's never been an issue before because shutting down the container terminates the log stream, whereas the ryuk container keeps the stream open, preventing the process from exiting. Changing the WaitStrategy of ryuk to HostPort works, though I will see if I can fix the wider issue.

**Comment by cristianrgreco** [comment] 2020-09-16 17:18
@kolychev PR is good to go 🙂 

It will be a major release as there are 2 breaking changes. Let me know if you want to review or if I can go ahead and release.

**Comment by kolychev** [comment] 2020-09-17 01:48
Hi @cristianrgreco, I have made a quick look and it all look very promising to me!
I am not familiar with docker-compose cases, did not use them in my tests yet. However the rest looks good to me :)
I will certainly give it a try, whenever you release it.

**Comment by cristianrgreco** [comment] 2020-09-18 21:09
@kolychev This is available in 4.0.2, I'm aware of an issue with docker-compose not working in GitLab but apart from that all is looking good. Please raise another issue if there are any problems - thanks again!

**Closed** 2020-09-18 21:09 UTC
Labels: enhancement
