### ISSUE TITLE
Memory leak when running testcontainers with jest

### ISSUE THREAD

**Issue by Zomono** [testcontainers/testcontainers-node#383] opened 2022-07-25 12:29 UTC
Hi,
I have some problems with high memory allocation in my unit test running with jest and node-testcontainers.
I have reduced the problem to a single test file that only starts and stops a single GenericContainer. 
After running this test a small amount of memory does not get garbage collected. 
This could be tested by running the test suite multiple times (in a single jest run) with and without the GenericContainer.

**Expected Behaviour**
If I am running the exact same test suite in jest that starts and stops a single GenericContainer instance, 
I expect the maximum amount of used memory to be the same for all test suites.

**Actual Behaviour**
The amount of used memory increases from run to run by ~15Mb. 
Running the same tests without the generic container stuff, the memory does not increase.

**Testcontainer Logs**
If you need any logs, please tell me.

**Steps to Reproduce**
1. Create a little project with jest installed. I am using typescript with ts-jest, but I do not think it is related to typescript. So a pure javascript version should be fine.
2. Create a basic jest config 
3. Create a file MemoryLeakBase.ts with content like shown below.
4. Create a up to 10 copies of the test suite MemoryLeak1 as shown below.
5. Run these tests with "node --inspect --expose-gc node_modules/jest/bin/jest.js --runInBand --logHeapUsage --no-cache --config ./jest.config.js MemoryLeak"
6. Inspect the console output from jest showing the used memory per test suite.
7. Remove the creation of the GenericContainer from the test function and try again.

**Environment Information**
- Operating System: Windows 10 64 bit
- Docker Version: 20.10.17, build 100c701
- Node version: 18.6.0
- Testcontainers version: 8.12.0

**My Console output**
~: node --inspect --expose-gc node_modules/jest/bin/jest.js --runInBand --logHeapUsage --no-cache --config ./jest.config.ts MemoryLeak
Debugger listening on ws://127.0.0.1:9229/41af492b-a25e-46e6-9971-9e5edcc9db1e
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
 PASS  tests/MemoryLeak6.test.ts (17.248 s, 657 MB heap size)
 PASS  tests/MemoryLeak5.test.ts (10.122 s, 672 MB heap size)
 PASS  tests/MemoryLeak4.test.ts (10.882 s, 685 MB heap size)
 PASS  tests/MemoryLeak3.test.ts (10.142 s, 698 MB heap size)
 PASS  tests/MemoryLeak2.test.ts (10.227 s, 710 MB heap size)
 PASS  tests/MemoryLeak1.test.ts (10.542 s, 723 MB heap size)

**MemoryLeakBase**

```
import { GenericContainer, StartedTestContainer, Wait } from "testcontainers"

export function runMemoryLeakTest() {
    let dockerContainer: StartedTestContainer
    jest.setTimeout(300_000)
    
    beforeAll(async () => {
        // testDb = await TestDb.create(databaseName);
        dockerContainer = await new GenericContainer("mcr.microsoft.com/mssql/server:2022-latest")
            .withEnv("ACCEPT_EULA", "Y")
            .withEnv("MSSQL_SA_PASSWORD", "Aa123456#")
            .withEnv("MSSQL_PID", "Express")
            .withExposedPorts(1433)
            .withWaitStrategy(Wait.forLogMessage(/.*Server is listening on.*1433.*/))
            .start()
    })
    
    afterAll(async () => dockerContainer?.stop({timeout: 30_000}))
    
    test("emptyTest", async () => {})
}
```

**MemoryLeak1**
```
import {runMemoryLeakTest} from "./MemoryLeakBase"

runMemoryLeakTest()

```

**Comment by cristianrgreco** [comment] 2022-10-15 19:04
Hi @Zomono, thanks for raising the issue.

I've been checking this locally and I think I've found the problem.

When you start a container, we also start a container called ryuk. We do not explicitly stop this container (it stops itself 10s after process termination). This means that as you run multiple instances of testcontainers, that you end up with a growing list of ryuk containers:

![Screenshot 2022-10-15 at 19 57 21](https://user-images.githubusercontent.com/10348798/196003716-a1ce7a19-53a4-40d1-b05f-4e5bc41a539d.png)

I can confirm that running the memory leak test with the following environment variable set results in no leak:

`TESTCONTAINERS_RYUK_DISABLED=true`

Let me know what you think, else I'll close this issue as I think this is working as intended.

**Comment by Zomono** [comment] 2022-10-15 20:46
Thanks for your investigation. 
Let me clarify the memory thing a little:
With the "maximum amount of memory" I mean the memory allocated by the node process only. Not for the whole system. 
And I expect it to stay roughly the same while executing the tests. 

The ryuk docker container may stay alive for a while (consuming memory on its own), but if I am calling "dockerContainer.stop()"  and the test suite is stopped/removed by jest, node-testcontainers should no longer hold any memory for container connections created in that test suite.

So could you please retry the test with ryuk enabled while only looking for the memory consumption of the node process that is running jest?

**Comment by cristianrgreco** [comment] 2022-10-15 22:06
> The ryuk docker container may stay alive for a while (consuming memory on its own), but if I am calling "dockerContainer.stop()" and the test suite is stopped/removed by jest, node-testcontainers should no longer hold any memory for container connections created in that test suite.

No, because the socket is [unref'd](https://github.com/testcontainers/testcontainers-node/blob/2ff9f2632424fad27535975fa497bae42be85bd5/src/reaper.ts#L112). 
This is on purpose so that ryuk is not attached to the node process, so the process can terminate without waiting on ryuk.

> With the "maximum amount of memory" I mean the memory allocated by the node process only. Not for the whole system. And I expect it to stay roughly the same while executing the tests.

See above.

Again, I have run your memory leak test and analysed the heap dump and can confirm the resources are those held by the socket, specifically the docker-modem. I have also run your memory leak test with ryuk disabled and can confirm it "fixes" the memory leak. If you have any opinion to the contrary, please provide evidence, else I will be closing this ticket.

**Comment by Zomono** [comment] 2022-10-16 09:38
Sorry. I thought calling the stop method would clean up all references and frees all memory including the ryuk connection. No reason here to wait until the ryuk container really has been shutdown by docker.
If it is on purpose that there are dangling connection after calling "stop", this ticket can be closed.

**Closed** 2022-10-16 10:54 UTC
Labels: triage
