### ISSUE TITLE
Error: Port XXX not bound after 10000ms  docker-compose -rabbitmq

### ISSUE THREAD

**Issue by johnico** [testcontainers/testcontainers-node#149] opened 2020-10-25 10:55 UTC
Hello,  I am trying to create a docker-compose file with rabbitmq service but got the following error:

**Error: Port 15691 not bound after 10000ms**

evreytime with diffrent port

my docker -compose
```
version: "3"

services:
  rabbitmq:
    image: rabbitmq:3
    ports:
      - "1234:5672" 
```

my code 

```
  environment = await new DockerComposeEnvironment('./test/', composeFile)
      .withStartupTimeout(new Duration(10, TemporalUnit.SECONDS))
      .up();
```

thanks

**Comment by cristianrgreco** [comment] 2020-10-25 11:55
Rabbit doesn't bind to all its exposed ports by default, meaning testcontainer's default wait strategy will timeout waiting for these ports to be bound. Use a log wait strategy instead:

```javascript
.withWaitStrategy("rabbitmq_1", Wait.forLogMessage("Server startup complete"))
```

Duplicate of https://github.com/testcontainers/testcontainers-node/issues/133. Would be a good idea to create a module for rabbit to stop people running into this.

**Closed** 2020-10-25 16:49 UTC
