### ISSUE TITLE
Failed to build Dockerfile with private registry as authorisation is missing

### ISSUE THREAD

**Issue by luismqoliveira** [testcontainers/testcontainers-node#204] opened 2021-05-01 21:14 UTC
I'm trying to build from a custom dockerfile and im getting error "Failed to build image" and i searched for the error and found that is in line 202 (isImageCached) from generic-container.js.
What i understood is that when i build a imagem from a dockerfile, if the "from" image is not cached it returns and error. Is that a bug? Shouldn't it push automatically when it's not cached? I have to build it first then i can run testcontainers with no errors.

**Comment by cristianrgreco** [comment] 2021-05-02 16:45
Hi @luismqoliveira

> if the "from" image is not cached it returns and error

That is not correct

> Shouldn't it push automatically when it's not cached

Push what?

Please share the error you got as well as a reproducible example

**Comment by luismqoliveira** [comment] 2021-05-03 14:56
Hi @cristianrgreco 
I'm sorry if you didn't understand my question, i'll try to explain it better.
I'm trying to create a container from a local dockerfile (which needs to download this library "FROM busybox:1.33.0 AS builder", but this happens with any library). Anytime i try to build this image if i don't have it locally cached it throws an error: "Error: Error: Failed to build image at GenericContainerBuilder.<anonymous> (.../node_modules/testcontainers/dist/generic-container.js:49:23" ). If i first build this image locally with docker build and then try to initialize the container it runs ok without any problem.
Here's my code:
` const buildContextCmpBackend = path.resolve(__dirname, "../../cmp-backend");
    const cmpBackendImage = await GenericContainer.fromDockerfile(buildContextCmpBackend, "Dockerfile.qa")
        .build();`
Here's my Dockerfile.qa:
`FROM registry.airc.pt/library/busybox:1.33.0 AS builder

ARG BUSYBOX_VERSION=1.31.0-i686-uclibc
ADD https://busybox.net/downloads/binaries/$BUSYBOX_VERSION/busybox_WGET /wget
RUN chmod a+x /wget

FROM registry.airc.pt/distroless/java:11

COPY --from=builder /wget /usr/bin/wget
etc...`

**Comment by cristianrgreco** [comment] 2021-05-03 16:50
> Shouldn't it pull the image if it is not cached on my machine

Yes that's right. I've just verified this by removing my local images and running this test:
https://github.com/testcontainers/testcontainers-node/blob/787c63fc39899ecc5986b3748830201af0614ff9/src/generic-container.test.ts#L378-L389

Set `DEBUG=testcontainers*` as an environment variable and re-try and share the error

**Comment by luismqoliveira** [comment] 2021-05-03 17:30
ok i found the problem. When i use a private registry like nexus to download the images which are cached there its throws an error.
If i download the image from docker hub its ok. I tried to put DEBUG flag like you said but i get no extra logs from image build. The only thing i get extra with "testcontainers*" are the logs of the started containers. It doesn't show any information about images builds

**Comment by cristianrgreco** [comment] 2021-05-03 17:52
Great, it should just be a case then of running docker login into your
private registry and trying again?

**Comment by luismqoliveira** [comment] 2021-05-04 09:32
@cristianrgreco 
I'm trying to use my proxy private repo, even thought i have made docker login it seems that testcontainers is not picking up the right credentials... I mean i use testcontainers with java and it works well, but this one is not capable of picking up my private registry. I've compared them both and docker host and socket path are the same. This error is on jenkins, but i did use docker login in that same repo.

> [ERROR] 2021-05-04T09:22:35.351Z testcontainers DEBUG Creating new DockerClient
> [ERROR] 2021-05-04T09:22:35.351Z testcontainers INFO Using default Docker host: localhost, socket path: /var/run/docker.sock
> [ERROR] 2021-05-04T09:22:35.352Z testcontainers DEBUG Creating new Reaper for session: 8eb712662a0b20c12d8cd42ae17994ed
> [ERROR] 2021-05-04T09:22:35.379Z testcontainers DEBUG No registry auth locator found for registry: "xpto"
> [ERROR] 2021-05-04T09:22:35.380Z testcontainers INFO Pulling image: xpto/cristianrgreco/ryuk:0.4.0
> [INFO] [10:22:35] E/launcher - Error: Error: (HTTP code 500) server error - Get https://xpto/v2/cristianrgreco/ryuk/manifests/0.4.0: no basic auth credentials 
> [INFO]     at /root/workspace/sid/sid-test-n-merge/frontend/node_modules/docker-modem/lib/modem.js:315:17
> [INFO]     at IncomingMessage.<anonymous> (/root/workspace/sid/sid-test-n-merge/frontend/node_modules/docker-modem/lib/modem.js:342:9)
> [INFO]     at IncomingMessage.emit (events.js:203:15)
> [INFO]     at endReadableNT (_stream_readable.js:1129:12)
> [INFO]     at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by cristianrgreco** [comment] 2021-05-04 10:01
Thanks for the info @luismqoliveira, this seems the problem:

`testcontainers DEBUG No registry auth locator found for registry: "xpto"`

Could you share the contents of `~/.docker/config.json` (make sure to omit any plain text or base 64 encoded creds if you have them)? That will help me see why your registry isn't being found.

Also I know you're substituting the registry name to `xpto` but that might be masking some issue. Is the real registry a URL?

Please also share what version of testcontainers you are using, as there was a change to how credentials are resolved in 7.8.0

**Comment by luismqoliveira** [comment] 2021-05-04 17:40
Hello @cristianrgreco 
This "xpto" is the URL of a nexus repository. I will try to find out a way to see the content of ~/.docker/config.json during a build on jenkins. I'm not really sure how but i'll try.
Couldn't you improve the log level so that the image creation of a custom docker file is printed as the logs of the containers are in "testcontainers*"? It would be easier to see what is causing the problem if the image creation was logged and it is in "docker build" command on local machine.

**Comment by cristianrgreco** [comment] 2021-05-04 17:57
I think the issue will be that xpto is represented in a way not currently
supported in your config.json file. If you are reproducing this issue
locally you could also share your local config.json file.

Regarding logs, the issue is clear from your previous message, we're
pulling from a private registry without providing authorisation.

**Comment by luismqoliveira** [comment] 2021-05-05 08:22
Here's my config.json file
{
	"auths": {
		"xpto": {
			"auth": "hash"
		},
		"xpto2": {
			"auth": "hash"
		}
	}
}

**Comment by cristianrgreco** [comment] 2021-05-05 08:52
I am confused 😄 This test shows that for your auth config, if your registry name is `xpto`, then it would return `true`, and you would not see `No registry auth locator found for registry: "xpto"`

https://github.com/testcontainers/testcontainers-node/blob/f58fe65acbbf1959c61416ad23a8727a7c8ca4e0/src/registry-auth-locator/auths.test.ts#L19-L22

There must be some discrepancy with the information I have provided

**Comment by cristianrgreco** [comment] 2021-05-05 09:10
Yes I think I know the issue, we are not forwarding auth information when building Docker images, I will raise a PR to implement this as soon as I have a chance. Thanks for raising @luismqoliveira

**Comment by luismqoliveira** [comment] 2021-05-05 21:56
Thank you @cristianrgreco im happy I could help. Keep your good work mate !

**Comment by cristianrgreco** [comment] 2021-05-06 09:07
Thanks @luismqoliveira 🙂 I've released the above PR in [7.10.0](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.10.0), could you please update and let me know how it goes?

**Comment by luismqoliveira** [comment] 2021-05-06 10:22
Hello @cristianrgreco I've upgraded to 7.10.0 and the behavior is strange. 
I'm trying to start 5 spring boot containers with custom Dockerfile from classpath. Each one of them have their unique Dockerfile but they are identic (the only diference is the jar name generated). I said the behavior is strange because sometimes i can successfully build two of them without any problem but in the third or other it fails with this error (but the image it tries to pull is from the same registry found one the last ones:

> DEBUG No registry auth locator found for registry: "https://index.docker.io/v1/" +47ms
>   testcontainers INFO Pulling image: 126f7a1c01cd020e2b49e2248dc9db49:e090f45322c638e01c617974c571ccbf +0ms
> [11:12:42] E/launcher - Error: Error: (HTTP code 404) unexpected - pull access denied for 126f7a1c01cd020e2b49e2248dc9db49, repository does not exist or may require 'docker login': denied: requested access to the resource is denied 
>     at .../frontend/node_modules/docker-modem/lib/modem.js:315:17
 
This is the success:

> DEBUG Preparing to build Dockerfile: /.../backend/Dockerfile.qa +7ms
>   testcontainers DEBUG No registry auth locator found for registry: "https://index.docker.io/v1/" +1ms
>   testcontainers DEBUG Found applicable registry auth locator for registry "xpto.pt": Auths +0ms
>   testcontainers INFO Building image '126f7a1c01cd020e2b49e2248dc9db49:e090f45322c638e01c617974c571ccbf' with context '/.../backend' +0ms

**Comment by cristianrgreco** [comment] 2021-05-06 10:40
Hmm, I'll need some more info to be able to reproduce, are you able to share any code which reproduces the issue? My understanding is that you have 5 identical Dockerfiles, all of which pull an image from a private registry, and when you build all of them, only a few of them succeed, is that correct? 

There should be more Docker build output as TRACE logs, could you share that as well?

**Comment by luismqoliveira** [comment] 2021-05-06 11:10
@cristianrgreco it's working. I hidden my comment because it was my mistake.
Thank you very much !

**Comment by cristianrgreco** [comment] 2021-05-06 11:32
That's great! I will close the issue then, thanks again 🙂

**Closed** 2021-05-06 11:33 UTC
Labels: bug
